#!/bin/sh
# pact views  -> regenerate every read-only view from frontmatter:
#   tasks/<plan>/STORIES_INDEX.md   one row per story in the plan
#   tasks/FEATURE_INDEX.md          one row per spec across all plans
#   docs/decisions/README.md        the DR table
#
# Views are a pure function of frontmatter; this never edits story/spec/DR files.
set -eu
. "$(dirname "$0")/lib.sh"

root=$(pact_project_root) || pact_die "not in a git repo"
GEN="<!-- generated by \`pact views\` — do not edit -->"

# ---- per-plan STORIES_INDEX ------------------------------------------------
for plan in "$root"/tasks/*/; do
  [ -d "$plan" ] || continue
  [ -d "$plan/epics" ] || continue
  out="$plan/STORIES_INDEX.md"
  {
    printf '# Stories — %s\n\n%s\n\n' "$(basename "$plan")" "$GEN"
    printf '| Story | Title | Epic | Status | Delivery | Blocked by |\n'
    printf '|---|---|---|---|---|---|\n'
    find "$plan/epics" -name '*.md' -path '*/stories/*' | sort | while read -r s; do
      id=$(fm_get "$s" id);       [ -n "$id" ] || continue
      title=$(fm_get "$s" title)
      epic=$(fm_get "$s" epic)
      status=$(fm_get "$s" status)
      delivery=$(fm_get "$s" delivery); [ -n "$delivery" ] || delivery='-'
      blk=$(fm_get "$s" blocked_by | sed 's/^\[//; s/\]$//; s/"//g')
      [ -n "$blk" ] || blk='-'
      printf '| %s | %s | %s | %s | %s | %s |\n' "$id" "$title" "$epic" "$status" "$delivery" "$blk"
    done
  } > "$out"
done

# ---- FEATURE_INDEX (one row per spec) -----------------------------------
fi_out="$root/tasks/FEATURE_INDEX.md"
if [ -d "$root/tasks" ]; then
  {
    printf '# Features\n\n%s\n\n' "$GEN"
    printf '| Spec | Slug | Type | Status | Epics done/total | Stories done/total |\n'
    printf '|---|---|---|---|---|---|\n'
    for spec in "$root"/docs/specs/*/spec.md; do
      [ -f "$spec" ] || continue
      sid=$(fm_get "$spec" id);   [ -n "$sid" ] || continue
      slug=$(fm_get "$spec" slug)
      stype=$(fm_get "$spec" type)
      sstat=$(fm_get "$spec" status)
      # find the plan for this spec: a story with spec: <sid>
      edone=0; etot=0; sdone=0; stot=0
      for st in $(grep -rl "^spec:[[:space:]]*$sid$" "$root"/tasks/*/epics/*/stories/*.md 2>/dev/null || true); do
        stot=$((stot+1))
        [ "$(fm_get "$st" status)" = done ] && sdone=$((sdone+1))
      done
      # epics = distinct epic dirs among those stories
      etot=$(grep -rl "^spec:[[:space:]]*$sid$" "$root"/tasks/*/epics/*/stories/*.md 2>/dev/null \
             | sed 's#/stories/.*##' | sort -u | wc -l | tr -d ' ')
      for ed in $(grep -rl "^spec:[[:space:]]*$sid$" "$root"/tasks/*/epics/*/stories/*.md 2>/dev/null \
                  | sed 's#/stories/.*##' | sort -u); do
        n=$(find "$ed/stories" -name '*.md' | wc -l | tr -d ' ')
        d=$(grep -rl '^status:[[:space:]]*done' "$ed"/stories/*.md 2>/dev/null | wc -l | tr -d ' ')
        [ "$n" -gt 0 ] && [ "$n" = "$d" ] && edone=$((edone+1))
      done
      printf '| %s | %s | %s | %s | %s/%s | %s/%s |\n' \
        "$sid" "$slug" "$stype" "$sstat" "$edone" "$etot" "$sdone" "$stot"
    done
  } > "$fi_out"
fi

# ---- decisions/README ---------------------------------------------------
dr_out="$root/docs/decisions/README.md"
if [ -d "$root/docs/decisions" ]; then
  {
    printf '# Decision Records\n\n%s\n\n' "$GEN"
    printf '| # | Title | Kind | Status | Date |\n'
    printf '|---|---|---|---|---|\n'
    for dr in $(find "$root/docs/decisions" -name '[0-9]*.md' | sort -r); do
      [ -f "$dr" ] || continue
      printf '| %s | %s | %s | %s | %s |\n' \
        "$(fm_get "$dr" id)" "$(fm_get "$dr" title)" "$(fm_get "$dr" kind)" \
        "$(fm_get "$dr" status)" "$(fm_get "$dr" date)"
    done
  } > "$dr_out"
fi

echo "ok: views regenerated"
